
services:

  postgres:
    image: postgres:16
    container_name: lincode-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lincode_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lincode_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    container_name: lincode-redis

    ports:
      - "6379:6379"

    restart: unless-stopped


  ai-service:
    build:
      context: ./ai-service

    container_name: lincode-ai

    ports:
      - "8001:8001"

    restart: unless-stopped


  backend:
    build:
      context: ./backend

    container_name: lincode-backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lincode_db
      REDIS_URL: redis://redis:6379
      AI_SERVICE_URL: http://ai-service:8001

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      ai-service:
        condition: service_started


volumes:
  postgres_data: