apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: lincode-backend-role
  namespace: lincode

rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
